version: "3.9"

services:
  api:
    build:
      context: ./
      target: production
    ports: 
      - "${APP_PORT}:4000"
    environment:
      - NODE_ENV=production
    env_file: .env.prod


### docker compose -f docker-compose.prod.yaml up
### docker compose -f docker-compose.prod.yaml up --build
### -d detatched mode