version: "3.9"

services:
  api:
    build:
      context: ./
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    command: npm test
    environment:
      - NODE_ENV=development
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30