#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run your tests inside a Docker container using docker-compose
# docker-compose -f ./docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from api

# Regular expression to validate commit message format (e.g., "ABC-123: Commit message")
echo "pre-push: Running tests before push..."
npm test
if [ $? -ne 0 ]; then
    echo "Tests must pass before push!"
    exit 1
fi
