#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push: Building Docker image and running tests before push..."

# Run your tests inside a Docker container using docker-compose
docker-compose -f ./docker-compose.test.yml up --abort-on-container-exit --exit-code-from api

if [ $? -ne 0 ]; then
    echo "Tests must pass before push!"
    exit 1
fi